### ISSUE TITLE
Logrotate cron error

### ISSUE THREAD

**Issue by mbugeia** [YunoHost/packages_old#37]
Hi,

I've notice a minor issue with logrotate's cron, almost everyday I received this email: 
subject: 
Anacron job 'cron.daily' on domain
Content: 
/etc/cron.daily/logrotate:
gzip: stdin: file size changed while zipping

I found the problem and the resolution explained here (in french): http://blog.claude.duvergier.fr/2013/09/logrotate-gzip-stdin-file-size-changed-while-zipping/

On my server there were 6 logrotate config with no delaycompress option:
mysql-server
razor
apt
metronome
unattended-upgrades
aptitude

Maybe it will be good to add delaycompress option to all the logrotate config to avoid the error.

**Comment by M0dM** [comment]
+1 

Same issue for me.
